DROP TABLE T_SCORESYSTEMSTUDENTS;
DROP TABLE T_SCORESYSTEMTEACHERS;
DROP TABLE T_SCORESYSTEMADMINS;
DROP TABLE T_SCORESYSTEMCOURSES;
DROP TABLE T_SCORESYSTEMSCORES;

CREATE TABLE T_SCORESYSTEMSTUDENTS(
       ACCOUNT VARCHAR2(25) PRIMARY KEY,
       PASSWORD VARCHAR2(25) NOT NULL,
       NAME     VARCHAR2(30) NOT NULL,
       AGE      VARCHAR2(10) NOT NULL,
       SEX      VARCHAR2(10) NOT NULL
);


CREATE TABLE T_SCORESYSTEMTEACHERS(
       ACCOUNT VARCHAR2(25) PRIMARY KEY,
       PASSWORD VARCHAR2(25) NOT NULL,
       NAME     VARCHAR2(30) NOT NULL,
       AGE      VARCHAR2(10) NOT NULL,
       TITLE      VARCHAR2(10) NOT NULL
);

CREATE TABLE T_SCORESYSTEMADMINS(
       ACCOUNT VARCHAR2(25) PRIMARY KEY,
       PASSWORD VARCHAR2(25) NOT NULL,
       NAME     VARCHAR2(30) NOT NULL,
       PERMISSIONS      VARCHAR2(10) NOT NULL
);

CREATE TABLE T_SCORESYSTEMCOURSES(
       COUNO VARCHAR2(20) PRIMARY KEY,
       COUNAME VARCHAR2(30) NOT NULL,
       TEACHERNO VARCHAR2(25) NOT NULL
);

CREATE TABLE T_SCORESYSTEMSCORES(
       STUNO VARCHAR2(20) ,
       COUNO VARCHAR2(20) ,
       SCORE NUMBER(5,2) ,
       CHANGEABLE VARCHAR2(5)
);

Alter table T_SCORESYSTEMSCORES
Add
    Constraints PK_UNIONPRIMARYKEY Primary Key (STUNO, COUNO);

alter table T_SCORESYSTEMSCORES
  add constraint CK_SCORE
  check (SCORE>=0 AND SCORE<=100);
  
alter table T_SCORESYSTEMSTUDENTS
  add constraint CK_STUDENTSSEX
  check (SEX='男' OR SEX='女');

INSERT INTO T_SCORESYSTEMADMINS VALUES('001','001','neo','1st');


INSERT INTO T_SCORESYSTEMSTUDENTS VALUES('001','001','Anderson','21','男');


INSERT INTO T_SCORESYSTEMTEACHERS VALUES('001','001','neo','21','校长');

INSERT INTO T_SCORESYSTEMTEACHERS VALUES('002','002','morphine','31','教授');

INSERT INTO T_SCORESYSTEMCOURSES
SELECT TRIM(课程号码),TRIM(教材),'001'
FROM 所有课程
WHERE 课程号码<3;

INSERT INTO T_SCORESYSTEMCOURSES
SELECT TRIM(课程号码),TRIM(教材),'002'
FROM 所有课程
WHERE 课程号码>=3 AND 课程号码<=6;

COMMIT;
